### PR TITLE
Show quest levels at Quest log

### PR DESCRIPTION
**Pull request by Apollyonn**

### CODE REVIEW

**Comment by Apollyonn** [comment]
I don't know if you want this to be part of this version of ElvUi

**Comment by Bunny67** [comment]
I think it's better to add to another addon. Because there are addons that perform the same function.

**Comment by crumdidlyumshis** [comment]
Maybe ElvUI_QuestLevel?

**Comment by Bunny67** [comment]
ElvUI_Enhanced or ElvUI_Bunny

**Comment by crumdidlyumshis** [comment]
ElvUI_Enhanced?

**Comment by Bunny67** [comment]
I mean, it's better to add it to ElvUI_Enhanced or ElvUI_Bunny.

**Comment by crumdidlyumshis** [comment]
Whichever I'm sure is fine. Maybe add it to ElvUI_Enhanced?

**Comment by Bunny67** [comment]
Perhaps:) Let Apollyonn decide :)

**Comment by Apollyonn** [comment]
Put it to Bunny :)

**Pull request closed without merging**
