### PR TITLE
Update Totembar

### PR DESCRIPTION
**Pull request by Apollyonn**

### CODE REVIEW

**Comment by Bunny67** [comment]
I don't understand why it is added
button position is already defined

**Comment by Apollyonn** [comment]
MultiCastRecallSpellButton:ClearAllPoints();
	MultiCastRecallSpellButton:SetPoint("LEFT", MultiCastActionButton4, "RIGHT", buttonSpacing, 0);

You cleared button points and then you anchored to MultiCastActionButton4, but when a low level player doesn't know all 4 totem spells the recall button stays hidden.

**Comment by Bunny67** [comment]
https://gist.github.com/Bunny67/d367789c759ee7323dceb7239d38fabe/revisions Try this

**Comment by Apollyonn** [comment]
This works now :D

**Pull request closed without merging**
