### PR TITLE
LFD / LFR Skins

### PR DESCRIPTION
**Pull request by Apollyonn**

### CODE REVIEW

**Comment by Apollyonn** [comment]
Before
main frame 1
After
main frame 2

Before
popup 1
After
popup 2

Before
queue 1
After
queue 2

Before
raid 1
After
raid 2

**Comment by crumdidlyumshis** [comment]
I like this update a lot! If only this functionality was in TBC haha

**Comment by crumdidlyumshis** [comment]
@Bunny67 Looks like this will conflict with your latest update. Boo 👎 This is a nice addition.

**Comment by Bunny67** [comment]
It can be added to ElvUI_Enhanced

**Pull request closed without merging**
